version: '3'
 
services:
    db:
        container_name: postgres
        image: postgres:latest
        ports:
          - "5432:5432"
        environment:
          POSTGRES_PASSWORD: dbpass
          POSTGRES_DB: docker_test
        volumes:
          - ./postgresql:/var/lib/postgresql
    apache_img_1:
        container_name: apache1
        build: ./apache
        volumes:
          - ./www:/var/www/html
        depends_on:
          - db
    apache_img_2:
        container_name: apache2
        build: ./apache
        volumes:
          - ./www:/var/www/html
        depends_on:
          - db
    haproxy_img:
        build: ./haproxy
        ports:
            - 80:80
        expose:
            - 80
        environment:
            - APACHE_1_IP=apache1
            - APACHE_2_IP=apache2
            - APACHE_EXPOSED_PORT=80
        depends_on:
          - apache_img_1
          - apache_img_2